[package]
name = "databaseutils"
version = "0.1.0"
authors = ["ToferC <cgeist7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webapp = { path = "../webapp" }
database = { path = "../database"}