-- Your SQL goes here

ALTER TABLE nodes
ADD COLUMN translation varchar(32) NOT NULL default '';

ALTER TABLE nodes
ADD COLUMN synonyms text[] NOT NULL default '{""}';

INSERT INTO nodes (node_name, domain_token)
VALUES
    ('white', 'person'),
    ('caucasian', 'person'),
    ('black', 'person'),
    ('african american', 'person'),
    ('african', 'person'),
    ('african canadian', 'person'),
    ('indigenous', 'person'),
    ('easter european', 'person'),
    ('western european', 'person'),
    ('mixed', 'person'),
    ('latino', 'person'),
    ('hispanic', 'person'),
    ('metis', 'person'),
    ('inuit', 'person'),
    ('native', 'person'),
    ('asian', 'person'),
    ('japanese', 'person'),
    ('korean', 'person'),
    ('chinese', 'person'),
    ('cambodian', 'person'),
    ('arab', 'person'),
    ('jewish', 'person'),
    ('irish', 'person'),
    ('han chinese', 'person'),
    ('french', 'person'),
    ('italian', 'person'),
    ('russian', 'person'),
    ('dutch', 'person'),
    ('swedish', 'person'),
    ('greek', 'person'),
    ('carribean', 'person'),
    ('parent', 'person'),
    ('grandparent', 'person'),
    ('caregiver to parents', 'person'),
    ('caregiver to children', 'person'),
    ('caregiver to family', 'person'),
    ('volunteer', 'person'),
    ('citizen', 'person'),
    ('landed immigrant', 'person'),
    ('work permit', 'person'),
    ('study permit', 'person'),
    ('undocumented', 'person'),
    ('able-bodied', 'person'),
    ('some physical disability', 'person'),
    ('significant physical disability', 'person'),
    ('vision impairment', 'person'),
    ('hearing impairment', 'person'),
    ('speech impairment', 'person'),
    ('slim body type', 'person'),
    ('average body type', 'person'),
    ('large body type', 'person'),
    ('property owner', 'person'),
    ('renter', 'person'),
    ('shelter user', 'person'),
    ('homeless', 'person'),
    ('neuro-typical', 'person'),
    ('some neuro-divergent', 'person'),
    ('significant neuro-divergent', 'person'),
    ('anxiety disorder', 'person'),
    ('mood disorder', 'person'),
    ('psychotic disorder', 'person'),
    ('eating disorder', 'person'),
    ('impulse control', 'person'),
    ('addiction disorder', 'person'),
    ('personality disorder', 'person'),
    ('obsessive-compulsive disorder', 'person'),
    ('post-traumatic stress disorder', 'person'),
    ('stress response syndrome', 'person'),
    ('dissociative disorder', 'person'),
    ('factitious disorder', 'person'),
    ('sexual or gender disorder', 'person'),
    ('somatic symptom disorder', 'person'),
    ('tic disorder', 'person'),
    ('struggling financial situation', 'person'),
    ('comfortable financial situation', 'person'),
    ('surplus financial situation', 'person'),
    ('low socioeconomic upbringing', 'person'),
    ('middle socioeconomic upbringing', 'person'),
    ('upper socioeconomic upbringing', 'person'),
    ('primary school education', 'person'),
    ('high school education', 'person'),
    ('trade school education', 'person'),
    ('college education', 'person'),
    ('university education', 'person'),
    ('masters level education', 'person'),
    ('doctorate level education', 'person'),
    ('anglophone', 'person'),
    ('francophone', 'person'),
    ('unilingual', 'person'),
    ('bilingual', 'person'),
    ('non-native english speaker', 'person'),
    ('non-native french speaker', 'person'),
    ('cisgender', 'person'),
    ('transgender', 'person'),
    ('transexual', 'person'),
    ('gender fluid', 'person'),
    ('non-binary', 'person'),
    ('genderqueer', 'person'),
    ('two spirit', 'person'),
    ('male', 'person'),
    ('female', 'person'),
    ('heterosexual', 'person'),
    ('homosexual', 'person'),
    ('lesbian', 'person'),
    ('gay', 'person'),
    ('bisexual', 'person'),
    ('pansexual', 'person'),
    ('bicurious', 'person'),
    ('questioning', 'person'),
    ('millenial', 'person'),
    ('gen y', 'person'),
    ('boomer', 'person'),
    ('young', 'person'),
    ('middle-aged', 'person'),
    ('old', 'person'),
    ('nearing retirement', 'person'),
    ('analyst', 'role'),
    ('program officer', 'role'),
    ('operations', 'role'),
    ('communications', 'role'),
    ('law enforcement', 'role'),
    ('correctional officer', 'role'),
    ('marketing professional', 'role'),
    ('scientist', 'role'),
    ('researcher', 'role'),
    ('security', 'role'),
    ('computer scientist', 'role'),
    ('lawyer', 'role'),
    ('auditor', 'role'),
    ('procurement officer', 'role'),
    ('hr officer', 'role'),
    ('executive', 'role'),
    ('finance officer', 'role'),
    ('supervisor', 'role'),
    ('psychologist', 'role'),
    ('teacher', 'role'),
    ('educator', 'role'),
    ('it officer', 'role'),
    ('leader', 'role'),
    ('networker', 'role'),
    ('entrepreneur', 'role'),
    ('policy analyst', 'role')
ON CONFLICT
    DO NOTHING;
